### ISSUE TITLE
PSR SimpleCache doesn't actually try to connect to the cache

### ISSUE THREAD

**Issue by michael-grunder** [cachewerk/relay#130]
### Discussed in https://github.com/cachewerk/relay/discussions/129

<div type='discussions-op-text'>

<sup>Originally posted by **tricarte** February 23, 2024</sup>
This is a sample code connecting to Redis using relay with its PSR16 cache implementation.

```php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Relay\Relay;
use CacheWerk\Relay\Psr\SimpleCache\RelayCache;

$relay = new Relay;
$relay->connect('127.0.0.1', 6379);

echo $relay->get('some:key') . "\n"; // This line works

$cache = new RelayCache($relay);
echo $cache->get('some:key') . "\n"; // This gives 'not connected' error
```

This is the full error:

```
PHP Fatal error:  Uncaught Relay\Exception: Not connected (RELAY_ERR_IO; relay.c:3513) in /home/user/repos/relay-redis/vendor/cachewerk/relay/src/Psr/SimpleCache/RelayCache.php:43
Stack trace:
#0 /home/user/repos/relay-redis/vendor/cachewerk/relay/src/Psr/SimpleCache/RelayCache.php(43): Relay\Relay->get()
#1 /home/user/repos/relay-redis/index.php(14): CacheWerk\Relay\Psr\SimpleCache\RelayCache->get()
#2 {main}

Next CacheWerk\Relay\Psr\SimpleCache\CacheException: Not connected (RELAY_ERR_IO; relay.c:3513) in /home/user/repos/relay-redis/vendor/cachewerk/relay/src/Psr/SimpleCache/RelayCache.php:47
Stack trace:
#0 /home/user/repos/relay-redis/index.php(14): CacheWerk\Relay\Psr\SimpleCache\RelayCache->get()
#1 {main}
  thrown in /home/user/repos/relay-redis/vendor/cachewerk/relay/src/Psr/SimpleCache/RelayCache.php on line 47
```

So, How am I supposed to construct the RelayCache instance?</div>

**Comment by michael-grunder** [comment]
The problem was we were creating a new (blank) `\Relay\Relay` object in our `RelayCache` constructor when we just wanted to use the one provided by the caller.
