### ISSUE TITLE
Apache starving at 100% cpu during cleanup

### ISSUE THREAD

**Issue by plieven** [cachewerk/relay#158]
## Description
From time to time I find apache processes starving at 100% cpu. A gdb backtrace reveals that it seems to be caused by the relay php extenstion:

```
(gdb) thread apply all bt full

Thread 1 (Thread 0x7ce533da2780 (LWP 655498) "apache2"):
#0  0x00007ce531cfe5bb in ck_rhs_next () from target:/usr/lib/php/20220829/relay.so
No symbol table info available.
#1  0x00007ce531c49b24 in relayCacheRhsUnwind (rhs=0x7ce52e9e4d10) at /root/relay/src/cache.c:2281
        key = {0x7ce52e66de38, 0x7ce52e9761a8, 0x7ce52e3a79e8, 0x7ce52e249a28, 0x7ce52e2b2d08, 0x7ce52e0b5748, 0x7ce52e6e9108, 0x7ce52e3dd3e8, 0x7ce52dcf5c08, 0x7ce52e8e6df8, 0x7ce52e1c6668, 0x7ce52df2e3f8, 0x7ce52e624538, 0x7ce52e13ca08, 0x7ce52e7b5048, 0x7ce52eaf52f8, 0x7ce52e91f1f8, 0x7ce52e9caa08, 0x7ce52e17d298, 0x7ce52e04e938, 0x7ce52e32e3a8, 0x7ce52e228a78, 0x7ce52deca758, 0x7ce52e0d2a28, 0x7ce52e2efb88, 0x7ce52ddda1f8, 0x7ce52e9af918, 0x7ce52dec40b8, 0x7ce52e0cbf08, 0x7ce52e89a748, 0x7ce52dc3e4a8, 0x7ce52e375838, 0x7ce52e9f6da8, 0x7ce52e6dd1c8, 0x7ce52e977438, 0x7ce52e16a1f8, 0x7ce52df60378, 0x7ce52e6ea378, 0x7ce52e38ad58, 0x7ce52e7140f8, 0x7ce52e93fbf8, 0x7ce52df16688, 0x7ce52e887568, 0x7ce52ddd7508, 0x7ce52e776e28, 0x7ce52df49848, 0x7ce52dc68668, 0x7ce52e25f3c8, 0x7ce52e2ad7b8, 0x7ce52ded4ce8, 0x7ce52e2b0c58, 0x7ce52e03e2b8, 0x7ce52e764298, 0x7ce52e8f4ca8, 0x7ce52e095ee8, 0x7ce52dcdaf28, 0x7ce52e162e78, 0x7ce52e6c9168, 0x7ce52df80be8, 0x7ce52eadcea8, 0x7ce52e8ef7c8, 0x7ce52e2838e8, 0x7ce52e3863c8, 0x7ce52dda5298, 0x7ce52df99638, 0x7ce52e814ec8, 0x7ce52dff78e8, 0x7ce52e058098, 0x7ce52e675488, 0x7ce52dfa3c28, 0x7ce52e899978, 0x7ce52e39bd18, 0x7ce52dc87c38, 0x7ce52e9bd2b8, 0x7ce52e7ab9e8, 0x7ce52e9595f8, 0x7ce52dcdb228, 0x7ce52e9530f8, 0x7ce52ddc3948, 0x7ce52e798808, 0x7ce52e831138, 0x7ce52ddda368, 0x7ce52df19c88, 0x7ce52e7a3c78, 0x7ce52df51f28, 0x7ce52dc87578, 0x7ce52df5f548, 0x7ce52e864928, 0x7ce52e8ac488, 0x7ce52dd7cdc8, 0x7ce52e3cadd8, 0x7ce52e3f2d68, 0x7ce52e65f798, 0x7ce52e982828, 0x7ce52e818b18, 0x7ce52dc46a78, 0x7ce52dfd2278, 0x7ce52e38abe8, 0x7ce52e884d48, 0x7ce52e291be8, 0x7ce52e621a28, 0x7ce52e074d48, 0x7ce52dfb0008, 0x7ce52e160808, 0x7ce52e2bbd58, 0x7ce52def2c78, 0x7ce52e1ad228, 0x7ce52dcfc408, 0x7ce52e642018, 0x7ce52df83328, 0x7ce52e21c598, 0x7ce52dd537d8, 0x7ce52dd58ee8, 0x7ce52e890698, 0x7ce52e2a1088, 0x7ce52df75008, 0x7ce52e9f6f18, 0x7ce52df69e48, 0x7ce52e93cc68, 0x7ce52de55c28, 0x7ce52dce9668, 0x7ce52e3eb818, 0x7ce52e291f08, 0x7ce52dc85778, 0x7ce52e6c2288, 0x7ce52dd89df8, 0x7ce52e271a58, 0x7ce52e71f6c8, 0x7ce52e3bd298, 0x7ce52e175bb8, 0x7ce52e187518, 0x7ce52df99a08, 0x7ce52e6cc998, 0x7ce52df5b6b8, 0x7ce52ea08aa8, 0x7ce52eaf2cb8, 0x7ce52e0320b8, 0x7ce52e01b4a8, 0x7ce52e7d0ad8, 0x7ce52dd46fd8, 0x7ce52dd5d2b8, 0x7ce52e78acc8, 0x7ce52eae2588, 0x7ce52e87fd28, 0x7ce52e06ddf8, 0x7ce52e2e3e28, 0x7ce52e2e2dd8, 0x7ce52ebec388, 0x7ce52de617e8, 0x7ce52e235058, 0x7ce52e65bc48, 0x7ce52ddc3488, 0x7ce52dd70818, 0x7ce52dd1b128, 0x7ce52e84a488, 0x7ce52dfa8938, 0x7ce52e74c398, 0x7ce52e12ba78, 0x7ce52e705608, 0x7ce52eaf3088, 0x7ce52e9151b8, 0x7ce52ebf58b8, 0x7ce52dffec38, 0x7ce52df3efa8, 0x7ce52df524e8, 0x7ce52e898388, 0x7ce52e39d348, 0x7ce52dccdeb8, 0x7ce52df1afd8, 0x7ce52e2fd848, 0x7ce52ead9c78, 0x7ce52dec1068, 0x7ce52dfb3938, 0x7ce52e2f1ea8, 0x7ce52ea0cda8, 0x7ce52e3930e8, 0x7ce52dd6a578, 0x7ce52dccefc8, 0x7ce52dd77af8, 0x7ce52e3ccb18, 0x7ce52e774418, 0x7ce52dc9a9e8, 0x7ce52e824c88, 0x7ce52e6382f8, 0x7ce52dd81e88, 0x7ce52eaeebf8, 0x7ce52de7c6d8, 0x7ce52e982548, 0x7ce52e1626c8, 0x7ce52dedf658, 0x7ce52dc55f08, 0x7ce52dee9e48, 0x7ce52e1fd708, 0x7ce52e1241c8, 0x7ce52eae1fa8, 0x7ce52e9444d8, 0x7ce52e6b3b38, 0x7ce52e3e9288, 0x7ce52e08e258, 0x7ce52e9a6e58...}
        it = {cursor = 0x0, offset = 5788}
        pos = 0
#2  0x00007ce531c4abfc in relayDBFlush (rdb=rdb@entry=0x7ce52e9e4c60, db=db@entry=0) at /root/relay/src/cache.c:2334
        section = {bucket = 0}
        res = 0
        aux = {m = 0x7ce531d3a770 <relayCacheAllocators>, map = 0x7ce52ea92e20, mode = 8, load_factor = 50, seed = 675727359, hf = 0x7ce531c49880 <relayCacheRhsHash>, compare = 0x7ce531c47b50 <relayCacheRhsCmp>}
        __func__ = "relayDBFlush"
#3  0x00007ce531c4ae25 in relayDBFlushAll (rdb=rdb@entry=0x7ce52e9e4c60, lock=lock@entry=1) at /root/relay/src/cache.c:2225
        i = 0
#4  0x00007ce531c4ae66 in relayEndpointReleaseDB (ep=0x7ce52dc0d4b0, rdb=0x7ce52e9e4c60) at /root/relay/src/cache.c:2356
No locals.
#5  0x00007ce531c4af1d in relayPLinkFree (plink=0x5e81262d3d50) at /root/relay/src/cache.c:997
No locals.
#6  relayPLinkFree (plink=0x5e81262d3d50) at /root/relay/src/cache.c:987
No locals.
--Type <RET> for more, q to quit, c to continue without paging--
#7  0x00007ce5338e7d9e in zend_llist_apply () from target:/usr/lib/apache2/modules/libphp8.2.so
No symbol table info available.
#8  0x00007ce531ccb7f1 in relayConnectionPoolDtor (res=0x5e8126189430) at /root/relay/src/relay.c:2175
        pool = 0x5e8126188140
#9  0x00007ce53390b309 in ?? () from target:/usr/lib/apache2/modules/libphp8.2.so
No symbol table info available.
#10 0x00007ce53390779e in zend_hash_graceful_reverse_destroy () from target:/usr/lib/apache2/modules/libphp8.2.so
No symbol table info available.
#11 0x00007ce5338f4bbe in ?? () from target:/usr/lib/apache2/modules/libphp8.2.so
No symbol table info available.
#12 0x00007ce53388eeaa in php_module_shutdown () from target:/usr/lib/apache2/modules/libphp8.2.so
No symbol table info available.
#13 0x00007ce53388ef59 in php_module_shutdown_wrapper () from target:/usr/lib/apache2/modules/libphp8.2.so
No symbol table info available.
#14 0x00007ce5339db981 in ?? () from target:/usr/lib/apache2/modules/libphp8.2.so
No symbol table info available.
#15 0x00007ce53401b5de in apr_pool_destroy () from target:/lib/x86_64-linux-gnu/libapr-1.so.0
No symbol table info available.
#16 0x00007ce533cbde27 in ?? () from target:/usr/lib/apache2/modules/mod_mpm_prefork.so
No symbol table info available.
#17 0x00007ce533cbec0b in ?? () from target:/usr/lib/apache2/modules/mod_mpm_prefork.so
No symbol table info available.
#18 0x00007ce533cbf027 in ?? () from target:/usr/lib/apache2/modules/mod_mpm_prefork.so
No symbol table info available.
#19 0x00007ce533cbf089 in ?? () from target:/usr/lib/apache2/modules/mod_mpm_prefork.so
No symbol table info available.
#20 0x00007ce533cbf7b3 in ?? () from target:/usr/lib/apache2/modules/mod_mpm_prefork.so
No symbol table info available.
#21 0x00005e81250ab6e0 in ap_run_mpm ()
No symbol table info available.
#22 0x00005e81250a31c2 in main ()
No symbol table info available.
```

## Expected Behavior
Clear module shutdown.

## Actual Behavior
Relay gets stuck during cleanup.

## Steps to Reproduce

1. Unclear how to reproduce. It seems that the DB struct contains a recursion and the cleanup routine loops infinetely.

## Relay diagnostics

```
# php --ri relay

relay

Relay Support => enabled
Relay Version => 0.9.1
Available cache => 16722880
Available serializers => php, json, igbinary, msgpack
Available compression => lzf, zstd, lz4
Binary UUID => 6aa71eb3-9964-42c9-a010-38a22e99c099
Git SHA =>  
Allocator => relay-mmap
Build OS => Ubuntu 22.04.5 LTS
Architecture => x86_64
OpenSSL version => OpenSSL 3.0.2 15 Mar 2022
License state => unknown
License memory cap => 0
License request id =>  
relay.enabled => true
relay.environment => development
relay.key =>  
relay.maxmemory => 16777216
relay.maxmemory_pct => 95
relay.eviction_policy => noeviction
relay.eviction_sample_keys => 128
relay.initial_readers => 128
relay.invalidation_poll_usec => 5
relay.default_pconnect => 1
relay.max_endpoint_dbs => 32
relay.loglevel => none
relay.logfile =>  
relay.session.compression => none
relay.session.compression_level => 0
relay.session.locking_enabled => 0
relay.session.lock_expire => 0
relay.session.lock_wait_time => 0
```

## Environment

* OS and version: Debian Bookworm
* PHP version: 8.2.26
* Redis version: 0.9.1

**Comment by michael-grunder** [comment]
Thanks. We shouldn't be explicitly unwinding on `MSHUTDOWN` in release builds. I'll take a look tomorrow when I'm back at my desk.

**Comment by michael-grunder** [comment]
Quick update for you. I haven't replicated the bug but am narrowing it down.

From the call stack, I can see Relay is unwinding the database in a fallback path. Essentially, when unwinding the database if Relay cannot allocate any memory at all for aux structures, there is a fallback unwinding which is memory stable. 

There must be an edge case in the fallback path causing the infinite loop. I'm trying to replicate it by forcing the fallback path to always run in a fuzz tester.

**Comment by plieven** [comment]
Hi Michael, have you been able to track this down?

**Comment by tillkruss** [comment]
Still trying to reproduce it. Are you able to trigger this reliably in an environment that we could take a look at?

**Comment by tillkruss** [comment]
@plieven Can you try Relay v0.10.1 to see if the error still occurs?

**Comment by plieven** [comment]
@tillkruss I will give it a try. My workaround was to set the memory limit to 0 which fixed the issue for me, but still was reasonable (about 3x) faster than phpredis in my case.

**Comment by tillkruss** [comment]
That great to hear.

**Comment by plieven** [comment]
@tillkruss Was setting the relay.maxmemory = 0 a valid workaround for whatever you fixed in v0.10.1?

**Comment by plieven** [comment]
No, I have not tried nginx with php-fpm. The server I am using relay is not a server with a high load in terms of client requests. Its not even a public available system. The main usage where phpredis turned out to be too slow is a php script that generates prometheus metrics from approx. 1500 keys stored in redis. This script took approx. 15 seconds with phpredis. With relay without caching it was cut to 4 seconds. With caching enabled and limiting cores to vcpus its down to approx. 1.5 seconds.

Btw, I noticed the new `relay.cap_endpoint_dbs` option. Altough the new relay.ini suggests its enabled by default it apparently is not.

**Comment by tillkruss** [comment]
@plieven You're right we'll fix that in the next release.

**Comment by plieven** [comment]
@tillkruss no hanging apache process yet.

**Comment by plieven** [comment]
@tillkruss issue seems to be fixed with v0.10.1
