### ISSUE TITLE
RELAY_ERR_TIMEOUT

### ISSUE THREAD

**Issue by nickchomey** [cachewerk/relay#24]
I just got a stream of errors in my WordPress debug.log. The page was loading fine however.

```
[12-Aug-2022 05:51:15 UTC] Relay\Exception: Timeout (RELAY_ERR_TIMEOUT) in /home/xyz.com/public_html/wp-content/object-cache.php:523
Stack trace:
#0 /home/xyz.com/public_html/wp-content/object-cache.php(523): Relay\Relay->ping()
#1 /home/xyz.com/public_html/wp-content/object-cache.php(220): WP_Object_Cache->__construct()
#2 /home/xyz.com/public_html/wp-includes/load.php(729): wp_cache_init()
#3 /home/xyz.com/public_html/wp-settings.php(131): wp_start_object_cache()
#4 /home/xyz.com/public_html/wp-config.php(140): require_once('...')
#5 /home/xyz.com/public_html/wp-load.php(50): require_once('...')
#6 /home/xyz.com/public_html/wp-blog-header.php(13): require_once('...')
#7 /home/xyz.com/public_html/index.php(17): require('...')
#8 {main}
[12-Aug-2022 05:51:18 UTC] Relay\Exception: Timeout (RELAY_ERR_TIMEOUT) in /home/xyz.com/public_html/wp-content/object-cache.php:523
Stack trace:
#0 /home/xyz.com/public_html/wp-content/object-cache.php(523): Relay\Relay->ping()
#1 /home/xyz.com/public_html/wp-content/object-cache.php(220): WP_Object_Cache->__construct()
#2 /home/xyz.com/public_html/wp-includes/load.php(729): wp_cache_init()
#3 /home/xyz.com/public_html/wp-settings.php(131): wp_start_object_cache()
#4 /home/xyz.com/public_html/wp-config.php(140): require_once('...')
#5 /home/xyz.com/public_html/wp-load.php(50): require_once('...')
#6 /home/xyz.com/public_html/wp-admin/admin-ajax.php(22): require_once('...')
#7 {main}
[12-Aug-2022 05:51:19 UTC] Relay\Exception: Timeout (RELAY_ERR_TIMEOUT) in /home/xyz.com/public_html/wp-content/object-cache.php:523
Stack trace:
#0 /home/xyz.com/public_html/wp-content/object-cache.php(523): Relay\Relay->ping()
#1 /home/xyz.com/public_html/wp-content/object-cache.php(220): WP_Object_Cache->__construct()
#2 /home/xyz.com/public_html/wp-includes/load.php(729): wp_cache_init()
#3 /home/xyz.com/public_html/wp-settings.php(131): wp_start_object_cache()
#4 /home/xyz.com/public_html/wp-config.php(140): require_once('...')
#5 /home/xyz.com/public_html/wp-load.php(50): require_once('...')
#6 /home/xyz.com/public_html/wp-cron.php(44): require_once('...')
#7 {main}
```

I rebooted my VPS (Ubuntu 20.04) and it stopped happening. Any idea what it could be from and what I could do in the future to fix it without a full reboot?

**Comment by tillkruss** [comment]
What version are you on?

**Comment by tillkruss** [comment]
I guess I'd see how often it occurs. Having a Redis request fail one or twice isn't too bad if you have millions a day.

**Comment by tillkruss** [comment]
>Also, is there any sort of auto-update mechanism when dowloading and installing directly rather than with a package manager?

You have to orchestrate that yourself.

>I'll keep an eye on it and report back if I notice anything. I'll close the ticket for now.

0.4.4 had a lot of stability improvements, let me know how it goes.
